package com.example.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.IdentityScopeType;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tb_nodeDaoConfig;

    private final tb_nodeDao tb_nodeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tb_nodeDaoConfig = daoConfigMap.get(tb_nodeDao.class).clone();
        tb_nodeDaoConfig.initIdentityScope(type);

        tb_nodeDao = new tb_nodeDao(tb_nodeDaoConfig, this);

        registerDao(tb_node.class, tb_nodeDao);
    }
    
    public void clear() {
        tb_nodeDaoConfig.getIdentityScope().clear();
    }

    public tb_nodeDao getTb_nodeDao() {
        return tb_nodeDao;
    }

}
